### ISSUE TITLE
will not render

### ISSUE THREAD

**Issue by cliffordx** [sethyuan/logseq-plugin-days#1]
I have a custom date format in my logseq config.edn like `EEEE, MMM do, yyyy`, is that the reason why the calendar does not render? 

<img width="314" alt="Screenshot 2022-11-01 at 1 34 12 PM" src="https://user-images.githubusercontent.com/7141739/199165948-198df731-482e-4e5a-bf2b-9da250a599db.png">
<img width="322" alt="Screenshot 2022-11-01 at 1 34 02 PM" src="https://user-images.githubusercontent.com/7141739/199165953-4be8f0b3-4260-42f8-b6f0-6cbfc69eb300.png">

**Comment by sethyuan** [comment]
Can you use the console to check what's the exact error? You can open the console using the menu.

![image](https://user-images.githubusercontent.com/3410293/199168557-b5afd436-a477-4337-9661-a53cb4db4253.png)

Open the console, wait a moment until it gets responsive, type the renderer as usual and hit Enter, you should see new red error messages in the console.

**Comment by cliffordx** [comment]
<img width="772" alt="Screenshot 2022-11-01 at 4 15 28 PM" src="https://user-images.githubusercontent.com/7141739/199188954-d9304aa2-88a7-4f8c-bb2b-f919d747a6db.png">

**Comment by sethyuan** [comment]
It looks like you're not installing the plugin the proper way. It's recommended that you install the plugin via the marketplace. If not possible, you can try enabling the developer mode in Logseq settings and use this to load the plugin:

![image](https://user-images.githubusercontent.com/3410293/199192309-b95fc74b-14b2-4b7e-9751-455e481f4e69.png)

**Comment by cliffordx** [comment]
Thanks. I installed it now via Marketplace and now it works. Previously, I can't see it on the Marketplace and may have improperly installed it manually. Thanks again for the support.
