### ISSUE TITLE
点击days的日历跳转到页面，非日志的正确页面。

### ISSUE THREAD

**Issue by VondeSong** [sethyuan/logseq-plugin-days#10]
初用days，发现点击日历的日期无法跳转到对应的日志页面。跳转到的页面是错误的。
已多次卸载重装，重启logseq，仍然无法解决问题。
![image](https://github.com/sethyuan/logseq-plugin-days/assets/54204388/563eac01-153c-40b7-9446-7b848d39943f)
这是我的格式。
![image](https://github.com/sethyuan/logseq-plugin-days/assets/54204388/6360b8bf-a90d-4969-949b-28ad255887a7)
配置中更改默认日期格式不生效
![image](https://github.com/sethyuan/logseq-plugin-days/assets/54204388/94783fbe-08ef-438c-b75f-dbb8107c677f)

**Comment by VondeSong** [comment]
我发现只有logseq语言为英文的时候，点击日历跳转的页面才是正确的。

**Comment by sethyuan** [comment]
我这边测试格式都是可以正确响应的，但有一个问题，Logseq日期处理上有个bug，EEE不是本地化，也就是虽然你选的中文，但Logseq出来的仍然是英文。而Days插件是本地化了的，所以出来的是中文的星期，这就导致页面名对不上出错。建议不要使用星期，或者使用星期的话把语言调整英文。

**Comment by VondeSong** [comment]
原来如此，受限于一些因素，我不得不用这个格式。今天发现即使我更改为英文，也是会出现出不来的情况，重启多次logseq有时候也无法解决。
