### ISSUE TITLE
每次重启Logseq，.kef-days-contentful的样式丢失。

### ISSUE THREAD

**Issue by VondeSong** [sethyuan/logseq-plugin-days#11]
打开Logseq
![1](https://github.com/sethyuan/logseq-plugin-days/assets/54204388/570a6177-87bb-410e-ad82-95d9fb904998)
需要手动重启插件后，才可以看到
![2](https://github.com/sethyuan/logseq-plugin-days/assets/54204388/00aebf07-1cc2-42e1-b017-155df62beb50)

**Comment by sethyuan** [comment]
你是不是看错了？我看你上面截图中也有kef-days-num呀。

**Comment by VondeSong** [comment]
我说错了，是这个div.kef-days-contentful ，这个用来显示对应日期是否有内容的这个div，重启后，是没有的。
手动重启插件才有

**Comment by VondeSong** [comment]
跟日志中内容太多有关系吗，刚刚突然想到是不是这个问题。我切换库，用别的内容比较少的库发现，第一次重启是有的。

**Comment by sethyuan** [comment]
应该没关系，先确保插件是最新版本再看看呢。

**Comment by VondeSong** [comment]
郁闷了，
![image](https://github.com/sethyuan/logseq-plugin-days/assets/54204388/fa90a002-4a1b-4687-a063-8837e5cdffd2)
多次重装了。前段时间没有这个问题，这半个月才发现的，每次都得手动重启。
切换库刚多次尝试发现，也是时有时无的。

**Comment by sethyuan** [comment]
没出来的时候console里有报什么错吗？

**Comment by VondeSong** [comment]
![image](https://github.com/sethyuan/logseq-plugin-days/assets/54204388/73cc14ed-bac0-4bae-a484-379ab4137a35)

**Comment by sethyuan** [comment]
没看到有什么错。你的日记日期格式是怎样的？用的语言是英语还是简体中文？

**Comment by VondeSong** [comment]
![image](https://github.com/sethyuan/logseq-plugin-days/assets/54204388/d1e5afe2-dc05-444c-bf78-51f7b083adef)
Fri, 2024/01/12这种格式的，days不兼容这个格式，就暂时只能用的英文语言

**Comment by sethyuan** [comment]
我待会儿有时间测试一下这种格式的，之间改过一版，可以兼容Logseq的英文星期了。

**Comment by sethyuan** [comment]
我这儿测试了下，用这种日期格式，无论是英文还是中文都是对的。

**Comment by sethyuan** [comment]
你的Days是咋写的？传的什么参数？

**Comment by sethyuan** [comment]
是不是你有多个graph，并且问题发生在切换graph时？如果不同的graph中的日期格式配置的不一样那么就有可能发生问题，我刚更新了一版解决了graph切换导致的问题。

**Comment by VondeSong** [comment]
更新新版本，经过多次测试发现。
我最大的一个graph，数据量比较大，如果重启的时候是这个库，days是有问题的。此时切换到其他库是days显示正常，再切换回来这个最大的graph，显示就正常了。
如果重启的时候不是这个最大的库，重启后，days显示正常。

**Comment by VondeSong** [comment]
{{renderer :days, *}}
![image](https://github.com/sethyuan/logseq-plugin-days/assets/54204388/84dc8fb1-9a56-4cfe-8f1f-cdfe51ef09c0)
![image](https://github.com/sethyuan/logseq-plugin-days/assets/54204388/0b317145-0d59-4db0-a865-110aa7e72f1a)
`{
    "template": "/page/:name",
    "data": {
        "name": "page"
    },
    "result": null,
    "path-params": {
        "name": "Jan 5th, 2024"
    },
    "path": "/page/Jan 5th%2C 2024",
    "queryParams": {
        "anchor": "block-content-editor"
    },
    "query-params": {
        "anchor": "block-content-editor"
    },
    "parameters": {
        "path": {
            "name": "Jan 5th, 2024"
        },
        "query": {
            "anchor": "block-content-editor"
        }
    },
    "pathParams": {
        "name": "Jan 5th, 2024"
    }
}`

**Comment by sethyuan** [comment]
从这个日志来看日记所采用的日期格式并不是你说的 ”Fri, 2024/01/12“ 这种，会不会你的这个库有日期格式错乱的问题？最好再检查一下库的日期格式设置。

建议备份好库然后试试re-index一遍，不行就清Logseq缓存。
