### ISSUE TITLE
Specify the month to be rendered

### ISSUE THREAD

**Issue by stdword** [sethyuan/logseq-plugin-days#15]
Hello!
Do you mind if I'll add the PR with the ability to specify the exact month to be rendered at first? Just like for the year view.

1) Which syntax is better for specifying month?
```
{{renderer :days, [[page]], all, 2024, 2}} // two value: year and month
{{renderer :days, [[page]], all, 2024-02}} // one value
```

2) How to be with second param when we need non-"all" value?
```
{{renderer :days, [[page]], -, 2024, 2}}  // explicitly ignore
{{renderer :days, [[page]], 2024, 2}}     // implicitly ignore 
```

**Comment by sethyuan** [comment]
Sure, please go ahead.

1. I prefer this syntax, `{{renderer :days, [[page]], all, 2024, 2}}`. It's easier to remember.
2. I think the explicit one is easier to remember and understand, and also easier to implement, `{{renderer :days, [[page]], -, 2024, 2}}`
