### ISSUE TITLE
Render days from date property

### ISSUE THREAD

**Issue by krillin666** [sethyuan/logseq-plugin-days#2]
Hi @sethyuan , 
Thanks for this amazing plugin !

I was wondering if it would be possible to display on the calendar queried blocks through the date property.
For example, if I use this template on a page **Logbook:**

``` 
date::
people::

    - Template Question A
    - Template Question B
```
And then used a simple query like  `{{query (and (property date) [[Logbook]]) }}`   

Thank you!

**Comment by sethyuan** [comment]
Not sure if I get you right, can you check the 2nd and the 3rd screencasts on the README page and see if they do what you want?

https://github.com/sethyuan/logseq-plugin-days/blob/master/README.en.md

**Comment by krillin666** [comment]
Hi ! 
What I was trying to say was that, if I have blocks inside a page called `meetings` for example and each block inside this page as the property `date` which is tied to a journal, if I query for those blocks nothing appears in the calendar.

Either with a simple query like `{{query (and (property date) [[meetings]] )}}` or a more advanced query to sort by journal date like the following:

```
#+BEGIN_QUERY
{
 :query [:find (pull ?b [*]) ?date-int
         :keys block date
         :where
         [?p :block/name "meetings"] ; name is always lowercase
         [?b :block/page ?p]
         [?b :block/properties ?prop]
         [(get ?prop :date) ?date]
         [?jpb :block/journal? true]
         [?jpb :block/original-name ?jbp-name]
         [(contains? ?date ?jbp-name)]
         [?jpb :block/journal-day ?date-int]
       ]
 :result-transform (fn [res] 
    (sort-by (fn [s] (get-in s [:block/properties :date-int])) > (map (fn [m] 
       (update (:block m) :block/properties 
           (fn [u] (assoc u :date-int (get-in m [:date]))
           ))
    ) res)))
 ;:view :pprint
}
#+END_QUERY
```

**Comment by sethyuan** [comment]
@krillin666 , I see. To provide a query for Days, you need to return journal pages in your query, that is, what you "pull" should be a journal page and not a block.

The 3rd video on the [README.en.md](https://github.com/sethyuan/logseq-plugin-days/blob/master/README.en.md) is showing how to use this feature. A template for an advanced query that returns journal pages is also provided on the bottom of the page.

**Comment by krillin666** [comment]
I see, so that would not be possible with that query ?
