### ISSUE TITLE
Incorrect date format?

### ISSUE THREAD

**Issue by kerim** [sethyuan/logseq-plugin-days#3]
I seem to have a problem with Days. It will show events in the calendar, but when I click on a calendar date it does not send me to the corresponding journal page. I think that is because it doesn't respect my preferred date settings? (No way to know this for sure, just a guess.)

:date-formatter "yyyy-MM-dd"
:journal/file-name-format "yyyy-MM-dd"

**Comment by sethyuan** [comment]
The plugin does take user's preferred date settings into consideration so the problem should be something else. Can you open the console (ctrl+shift+i or cmd+shift+i), click on a date and check what the error is?

**Comment by kerim** [comment]
Hmm. I don't see any error message when I click on something... But it doesn't send me to a proper page either.

**Comment by lef-est** [comment]
> :date-formatter "yyyy-MM-dd" :journal/file-name-format "yyyy-MM-dd"

I use the same format but don't have this bug. The problem may be elsewhere.

**Comment by sethyuan** [comment]
@kerim Can you disable all other plugins, restart Logseq and try again? If it worked, there may be a conflict with some other plugin.

**Comment by kerim** [comment]
That doesn't help. Next I want to try to completely uninstall and re-install Days. I remember in the past having problems with plugins that didn't update properly.

**Comment by kerim** [comment]
OK. That seems to have helped. I uninstalled, deleted the settings file, and then re-installed (after a restart). Now it is working again!

**Comment by kerim** [comment]
Hmm. That fixed it, but the issue came back after I turned on the other plugins. I'll have to go through and identify the conflict, because I use a bunch of plugins and it will take time to identify which one is causing problems...

**Comment by kerim** [comment]
No, it isn't a conflict. Deleting and reinstalling fixes the problem, but it comes back after restart, even if I don't add any other plugins.
