### ISSUE TITLE
Feature request: Year range

### ISSUE THREAD

**Issue by cliffordx** [sethyuan/logseq-plugin-days#4]
The plugin is very useful for a particular year. However, I wanted to get a range of particular page or tag for multiple span of years. Is it possible or doable?

Thanks!

**Comment by sethyuan** [comment]
There is no built-in support for multiple years, but it can be easily achieved by creating multiple yearly views. E.g.:

```
{{renderer :days-year, [[page]], 2000}}
{{renderer :days-year, [[page]], 2001}}
```

**Comment by cliffordx** [comment]
yup that what's I already did. What I'm hoping if it can do like:

`{{renderer :days-year, [[page]], 2000-2003}}`

**Comment by sethyuan** [comment]
Got it. I can add it to my TODO list. BTW, how would you prefer to switch between the years? Maybe 2 arrows like in the calendar view?

**Comment by sethyuan** [comment]
@cliffordx This is implemented now, there are new arrow buttons to switch between years. I've also recorded new demonstration videos and put them on the README. You can pass a starting year or no year at all to use this feature.
