### ISSUE TITLE
Forgotten line of code

### ISSUE THREAD

**Issue by stdword** [sethyuan/logseq-plugin-days#5]
This [forgotten line of code](https://github.com/sethyuan/logseq-plugin-days/blob/13d505a0d97989ef541b6c8cc8ddf233f5a20e20/src/libs/query.js#L296) breaks plugin work

If property value contains empty string we get an error: `Uncaught TypeError: Cannot read properties of undefined (reading 'replace')`

**Comment by sethyuan** [comment]
OMG, thanks for letting me know. I'll check the code.

**Comment by sethyuan** [comment]
The extra line is removed, please give new version a try.

**Comment by stdword** [comment]
It works now, thanks!

Another note: There is a little special case with this feature, that displays not so nice:
<img width="600px" src="https://github.com/sethyuan/logseq-plugin-days/assets/1984175/ac064d8e-ef0e-4254-bf98-64ce95c85eb1"/>

Possible behaviors:
- Display the dot, instead if vertical line
- Display specified property value (`keywords` in my demo)

**Comment by sethyuan** [comment]
I don't think it's a good idea to just use a random property as the content to be displayed, block content should represent the block itself. It's not designed to be used with properties.

**Comment by stdword** [comment]
> I don't think it's a good idea to just use a random property as the content to be displayed, block content should represent the block itself. It's not designed to be used with properties.

Sure, I'm just offer my ideas.
Now it is not designed to be used without block content.

**Comment by sethyuan** [comment]
No problem. The reason behind this design is that the content of a block is much like the name of a page, they both represent the uniqueness of the block. In practice, page properties (`when` in your case) are more often used.
