### ISSUE TITLE
DONE and CANCELED show up with the latest update

### ISSUE THREAD

**Issue by cliffordx** [sethyuan/logseq-plugin-days#6]
Just updated to v. 0.12.1 and the DONE and CANCELED show up. See attached screenshot:

<img width="352" alt="Screenshot 2023-07-12 at 5 35 24 PM" src="https://github.com/sethyuan/logseq-plugin-days/assets/7141739/f07e4211-5538-461c-952b-72bd74eefea4">

What could be possibly the reason why?

**Comment by sethyuan** [comment]
Scheduled and Deadlines are now being shown in the calendar in the latest release, you must have scheduled or deadline on these todos.

I can stripe the prefix of the todos, does that work for you?

**Comment by cliffordx** [comment]
I have SCHEDULED AND DEADLINE but after clicking DONE it show up. It should not show up after its done, right?

**Comment by sethyuan** [comment]
The current behavior doesn't take consideration of a task's status, it only looks if it has a SCHEDULED/DEADLINE. I can adjust this behavior to make it consider a task's status, say DONE and CANCELLED are not shown.

**Comment by sethyuan** [comment]
It's implemented, please have a try. @cliffordx
