### ISSUE TITLE
[Feature Request] Add edit-on-click behaviour for all calendars

### ISSUE THREAD

**Issue by stdword** [sethyuan/logseq-plugin-days#8]
If i need to modify block with calendar I've faced with issue:
<img width="600px" src="https://github.com/sethyuan/logseq-plugin-days/assets/1984175/cb11f3ae-ff5a-4d6c-a866-1552b05f4e35"/>

The only way to edit block is to edit another one, then navigate with arrows to required.

Solution: Add edit-on-click behaviour for all calendars or at least a special edit button
Required code: [on-click](https://github.com/stdword/logseq13-full-house-plugin/blob/main/src/logic.ts#L248) + [handler](https://github.com/stdword/logseq13-full-house-plugin/blob/main/src/app.ts#L295-L299)

**Comment by sethyuan** [comment]
Yeah, you're right, I can add an edit button.

**Comment by sethyuan** [comment]
@stdword It's done, a edit button is added.

**Comment by stdword** [comment]
Thank you! Very nice!

Do you plan to add the same button for simple calendars?
<img width="365" alt="CleanShot 2023-08-16 at 11 10 22@2x" src="https://github.com/sethyuan/logseq-plugin-days/assets/1984175/90365c27-21a8-4ab2-be38-3eacd5f650db">

**Comment by sethyuan** [comment]
Yeah, let me do it.
