### ISSUE TITLE
[Feature Idea] Add consistency between different commands

### ISSUE THREAD

**Issue by stdword** [sethyuan/logseq-plugin-days#9]
1. To call `:days` for current page I need to use:
   ```
   {{renderer :days, *}}
   ```

   To call `:days-year` for current page it doesn't work the same way:
   ```
   {{renderer :days-year, *}}
   ```

   I need to use full page name:
   ```
   {{renderer :days-year, [[Page Name]]}}
   ```
   **Idea**: add `*`-ability for `:days-year`

2. The command `:days` (and `:days-year` too) doesn't work without params:
   ```
   {{renderer :days}}
   {{renderer :days-year}}
   ```
    **Idea**: make it work as `*` by default for easy usage for current page.

**Comment by sethyuan** [comment]
Thanks for the suggestions! To make things clear, by current page, you mean the main page that is being edited, or the page the Day's renderer is on?

I used to use "*" for the first case, and no argument for the second. However both :days and :days-year have a 2nd argument, if we omit the first argument, the second one would become the first.

**Comment by stdword** [comment]
Current page is the main page that being edited:
![CleanShot 2023-08-19 at 15 50 46@2x](https://github.com/sethyuan/logseq-plugin-days/assets/1984175/0a37f3a8-01fc-4619-8517-27fa62b79371)

**Comment by sethyuan** [comment]
Got it, I can add `*` support for :days-year, but it may take some time since I have other priorities to look, kind of too busy recently.

**Comment by sethyuan** [comment]
:days-year support for `*` is added.

**Comment by stdword** [comment]
Checked: it works 🙏

Special case: with aliases:
On page «THE PAGE»:
- alias:: THE ALIAS
- {{renderer :days-year, *}} — works for journal records with ref [[THE PAGE]], but doesn't work for ref [[THE ALIAS]]

**Comment by sethyuan** [comment]
Right now, aliases in Logseq must be handled manually by plugins because the alias and the original page are actually 2 different pages, but I think this problem should be and is better dealt with by Logseq itself. I mean they shouldn't be 2 pages really but a single page with 2 or more names. Dealing with this in the plugin level is very cumbersome.
